apiVersion: v1
kind: ConfigMap
metadata:
  name: getfit-config
  namespace: getfit
  labels:
    app.kubernetes.io/part-of: getfit
data:
  NODE_ENV: "production"
  PORT: "3000"
  POSTGRES_DB: "getfit"
  POSTGRES_USER: "postgres"
